### ISSUE TITLE
Can't I generate a 3D mesh

### ISSUE THREAD

**Issue by user-deng** [NiklasFreymuth/AMBER#1]
Thank you very much for your great work. I am trying to generate a 3D mesh on a step file, but did I not implement this code? Can you help me?
![123](https://github.com/NiklasFreymuth/AMBER/assets/139295830/816252f0-e24c-4311-bf11-3eda6be9b556)

**Comment by NiklasFreymuth** [comment]
Hi!

It seems like you are trying to instantiate a Poisson problem on your 3d mesh. In the provided code, each mesh-geometry pair is also associated with some system of equations (called fem_problem in the code). For purely geometry-based mesh generation, we use a dummy problem that returns an all-zero solution over a given mesh. There should be an example on how to access in the configs for the 3d console task.
Let me know if there are any additional issues :)

**Comment by user-deng** [comment]
Really? But I couldn't find the example and configuration file you mentioned, and I would greatly appreciate it if you could give me some guidance.

**Comment by NiklasFreymuth** [comment]
This snippet from [this file](https://github.com/NiklasFreymuth/AMBER/blob/main/configs/amber/amber_runs.yaml) should do the trick:
---
```
params:
  task:
    fem:
      domain:
        dimension: 3
        domain_type: step_file_domain
      pde_type: null
```
"pde_type: null" selects the dummy fem_problem, which should enable you to train the approach on your 3d step files and meshes.

**Comment by user-deng** [comment]
Yes, I have already done so and set "mesh_datasetname" to "console", unfortunately, I still reported an error. And the function I want to implement is to perform grid partitioning on any step file. The code is too large, and I feel like I need to start
![111](https://github.com/NiklasFreymuth/AMBER/assets/139295830/abf9f3f2-0d37-4075-9d13-06d27c9ea536)
![222](https://github.com/NiklasFreymuth/AMBER/assets/139295830/061e52ee-b96a-4366-bc63-fdb082e5b360)

**Comment by user-deng** [comment]
Thank you for the reminder. I followed your suggestion and reset the console, but still encountered an error.
![12](https://github.com/NiklasFreymuth/AMBER/assets/139295830/59d451cb-a232-48b9-ac87-6d5c4be588c5)
![21](https://github.com/NiklasFreymuth/AMBER/assets/139295830/f6675742-784f-4c7a-a598-02fffc5fb739)

**Comment by NiklasFreymuth** [comment]
Seems like you are now getting to the training, which is good. The code suggests that there is no training data to create a batch from.
Maybe you can have a look at the (training) dataloader and its initialization to figure out why there is no training data.

**Comment by user-deng** [comment]
Thank you very much for your suggestion! I have another question, can the trained weights be called to perform mesh partitioning on any step after the 3D training is completed? Is there an implementation in the code? Can it be done?

**Comment by NiklasFreymuth** [comment]
There's currently no designated evaluation script. If you only need to evaluate once, you can put the respective data into the test set, which is only evaluated and recorded after training is finished. Similarly, there is an option to load a checkpoint in the model config file by copying the original config and adding these parameters:
```
params:
  algorithm:
    checkpoint:
      experiment_name: $your_experiment
      iteration: null # leave empty for final iterations
      repetition_idx: $your_seed
```


If you want to load the model for some downstream application after training has finished, you can do so with this code snippet:
```
    def load_checkpoint(self, checkpoint_path: str) -> Tuple[AbstractArchitecture, AbstractRunningNormalizer]:
        """
        Loads the model and normalizer from the specified checkpoint.

        Args:
            checkpoint_path (str): The file path to the model checkpoint.
        """
        checkpoint_path = Path(checkpoint_path)

        state_dict_path = checkpoint_path / f"ckpt.pt"
        normalizer_path = checkpoint_path / f"ckpt_norm_params.pkl"
        architecture = AbstractArchitecture.load_from_path(
            state_dict_path=state_dict_path,
            device=self.device,
        )
        architecture.to(self.device)
        # load environment normalizer if available. Load from same iteration as network
        if normalizer_path.exists():
            normalizer = AbstractRunningNormalizer.load(checkpoint_path=normalizer_path)
            normalizer.to(self.device)
        else:
            normalizer = DummyRunningNormalizer()
        architecture.train()

        return architecture, normalizer
```
When calling the model, just remember to apply the input/output normalization and prediction transformations as done during training, which you can copy over from the routines in amber.py :)

**Comment by user-deng** [comment]
Excuse me again, when I am training on the "console", setting "num_train_pdes" to 1 still exceeds the memory. What should I do?
num_train_pdes: 1
num_val_pdes: 1
num_test_pdes: 1
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 318.00 MiB. GPU 0 has a total capacty of 23.69 GiB of which 230.94 MiB is free. Process 377515 has 23.46 GiB memory in use. Of the allocated memory 22.01 GiB is allocated by PyTorch, and 419.47 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by NiklasFreymuth** [comment]
This issue seems to be related with your batching. Try to increase the tolerance for the batch size finder, or manually set a maximum batch size.

**Comment by user-deng** [comment]
Shouldn't it be a decrease in batch size? But my batch size has already been set to 1

**Comment by NiklasFreymuth** [comment]
Assuming your batch size is already small enough, try using a smaller GNN. In either case, this should not be an issue of the algorithm itself, but of your (parameterization of the) batching

**Comment by user-deng** [comment]
I just set a larger batch size of 3 and it did run successfully. Thank you, but it's a bit beyond my understanding.

**Comment by NiklasFreymuth** [comment]
Interesting... Glad you got it to work!

**Comment by user-deng** [comment]
I'm here again~Didn't you visualize this grid after conversion?


[scalars] Default/Self Memory Usage: 5.589e+03
[scalars] Default/Child Memory Usage: 2.487e+03
[scalars] Default/Total Memory Usage: 3.600e+00
[Recorder] Finished recording iteration 7
 44%|█████████████████▉                       | 112/256 [00:52<00:34,  4.19it/s]
