### ISSUE TITLE
Hello, did Expert Mesh participate in the model prediction process? And what was its role when doing the inference?

### ISSUE THREAD

**Issue by user-deng** [NiklasFreymuth/AMBER#6]
![1](https://github.com/user-attachments/assets/3bcef5b1-bcfe-45a3-9769-4398e102d4ec)

**Comment by NiklasFreymuth** [comment]
The expert mesh is used to project the labels on the sequence of intermediate meshes. If you want to use AMBER for inference only, you could either input a constant label, or re-write the code to make this parameter optional :)
